### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by iCTX0780** [mosh-hamedani/vidly-api-node#1]
when two integration tests run using same port. one of them gets 
`listen EADDRINUSE :::3900`

**steps to reproduce**
1. clone
2. npm i
3. mongod
4. node seed.js
5. npm test

I'm using 

- Node version 8.11.3
- NPM version 5.6.0

**Comment by nflaig** [comment]
In `package.json` [line 9](https://github.com/mosh-hamedani/vidly-api-node/blob/master/package.json#L9) you have to add the `--runInBand` flag to the test script.

**Comment by iCTX0780** [comment]
thanks @nflaig 
that fixed my problem.
