### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by GeorgeSteshenko** [mosh-hamedani/vidly-api-node#17]
I'm going through React course at the moment and got stuck on Setting up the node backend.
I've cloned repo and under the vidly-api-node tried to run command npm i . As the result I've got this:
`npm i

> fsevents@1.2.4 install /Users/yegorsteshenko/Projects/vidly-api-node/node_modules/fsevents
> node install

node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@11.9.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../node_modules/nan/nan.h:203:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:337:28: warning: 'New' is deprecated: Use Isolate*
      version [-Wdeprecated-declarations]
  return v8::StringObject::New(value).As<v8::StringObject>();
                           ^
/Users/yegorsteshenko/.node-gyp/11.9.0/include/node/v8.h:5241:3: note: 'New' has been explicitly marked
      deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/yegorsteshenko/.node-gyp/11.9.0/include/node/v8config.h:326:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:1034:44: warning: 'ToString' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString();
                                           ^
/Users/yegorsteshenko/.node-gyp/11.9.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly
      marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/yegorsteshenko/.node-gyp/11.9.0/include/node/v8config.h:326:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:1044:27: warning: 'WriteUtf8' is deprecated: Use Isolate* version
      [-Wdeprecated-declarations]
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                          ^
/Users/yegorsteshenko/.node-gyp/11.9.0/include/node/v8.h:2753:3: note: 'WriteUtf8' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/yegorsteshenko/.node-gyp/11.9.0/include/node/v8config.h:326:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../fsevents.cc:63:6: warning: field 'async_resource' will be initialized after field 'lockStarted'
      [-Wreorder]
   : async_resource("fsevents:FSEvents"), lockStarted(false) {
     ^
4 warnings generated.
  SOLINK_MODULE(target) Release/fse.node
  COPY /Users/yegorsteshenko/Projects/vidly-api-node/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

> bcrypt@1.0.3 install /Users/yegorsteshenko/Projects/vidly-api-node/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v67-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@11.9.0 (node-v67 ABI) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v67-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@11.9.0 (node-v67 ABI) (falling back to source compile with node-gyp)
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
rm: ./Release/.deps/Release/obj.target/bcrypt_lib/src/blowfish.o.d.raw: No such file or directory
make: *** [Release/obj.target/bcrypt_lib/src/blowfish.o] Error 1
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/11.9.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/yegorsteshenko/Projects/vidly-api-node/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/Users/yegorsteshenko/Projects/vidly-api-node/node_modules/bcrypt/lib/binding"
gyp ERR! cwd /Users/yegorsteshenko/Projects/vidly-api-node/node_modules/bcrypt
gyp ERR! node -v v11.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/11.9.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/yegorsteshenko/Projects/vidly-api-node/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/yegorsteshenko/Projects/vidly-api-node/node_modules/bcrypt/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/yegorsteshenko/Projects/vidly-api-node/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/11.9.0/bin/node" "/Users/yegorsteshenko/Projects/vidly-api-node/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/yegorsteshenko/Projects/vidly-api-node/node_modules/bcrypt
node-pre-gyp ERR! node -v v11.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/11.9.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/yegorsteshenko/Projects/vidly-api-node/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/yegorsteshenko/Projects/vidly-api-node/node_modules/bcrypt/lib/binding' (1)
error: error opening './Release/.deps/Release/obj.target/bcrypt_lib/src/bcrypt.o.d.raw': No such file or
      directory
1 error generated.
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/11.9.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/yegorsteshenko/Projects/vidly-api-node/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/Users/yegorsteshenko/Projects/vidly-api-node/node_modules/bcrypt/lib/binding"
gyp ERR! cwd /Users/yegorsteshenko/Projects/vidly-api-node/node_modules/bcrypt
gyp ERR! node -v v11.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN vidly@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@1.0.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yegorsteshenko/.npm/_logs/2019-10-10T12_26_57_005Z-debug.log
`
Here is an attached complete log of this run:
[2019-10-10T12_26_57_005Z-debug.log](https://github.com/mosh-hamedani/vidly-api-node/files/3712541/2019-10-10T12_26_57_005Z-debug.log)

**Comment by GeorgeSteshenko** [comment]
Okay, seems like install/update of bcrypt up to 2.0.0 version did help. Corresponding tables has been created, but w/o users table. Only genres and movies.

**Comment by prawnydagrate** [comment]
This was happening to me too. I had to run the following:
```sh
$ npm i bcrypt@3.0.7
$ npm i
```

**Comment by codewithshahan** [comment]
> This was happening to me too. I had to run the following:
> 
> ```shell
> $ npm i bcrypt@3.0.7
> $ npm i
> ```

This version doesn't work now. You have to install: 

> npm i bycrypt@5.0.1
> npm i

You just need to update the latest version of bycrypt.

**Comment by mdarif** [comment]
> > This was happening to me too. I had to run the following:
> > ```shell
> > $ npm i bcrypt@3.0.7
> > $ npm i
> > ```
> 
> This version doesn't work now. You have to install:
> 
> > npm i bycrypt@5.0.1
> > npm i
> 
> You just need to update the latest version of bycrypt.

+1

Updating bycrypt npm to latest version fixes the issue, at the same time git source code should also be updated to reflect the same.

**Comment by hassanmoin172** [comment]
delete node modules then npm i ,its remove the bycrpt error
