### ISSUE TITLE
URL String Parser is deprecated / Current Server Discovery and Monitoring engine

### ISSUE THREAD

**Issue by therabithole** [mosh-hamedani/vidly-api-node#18]
(node:6448) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:6448) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Done!

**Comment by Turkinolith** [comment]
Still an issue, also get this one now:
(node:20464) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.

**Comment by codingChewie** [comment]
Need to update _db.js_ in the **startup** directory:

from:

```javascript
module.exports = function() {
  const db = config.get('db');
  mongoose.connect(db)
    .then(() => winston.info(`Connected to ${db}...`));
}
```

to:
```javascript
module.exports = () => {
  const db = config.get('db')
  mongoose
    .connect(db, { useNewUrlParser: true, useUnifiedTopology: true })
    .then(() => winston.info(`Connected to ${db}...`))
}
```
