### ISSUE TITLE
Unable to generate auth token

### ISSUE THREAD

**Issue by vedant0712** [mosh-hamedani/vidly-api-node#19]
![Annotation 2019-11-05 125623](https://user-images.githubusercontent.com/44584376/68187092-bfa1b280-ffcb-11e9-8cbf-c8e2e973fb3d.png)
Can anyone help me with this?

**Comment by Zucci-Daniel** [comment]
please help!! i get the same error as @vedant0712, i've been stocked and searching for help, someone pls!
