### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by rajeevkuruganti** [mosh-hamedani/vidly-api-node#3]
_I have run_ 
node seed.js
**and I get the below error. I retyped the function again and deleted the existing line in the JS file and still did not work. 
Can you assist me please?**

D:\Projects\ReactJS\vidly-api-node\seed.js:41
async function seed() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

**Comment by PandaSobao** [comment]
> _I have run_
> node seed.js
> **and I get the below error. I retyped the function again and deleted the existing line in the JS file and still did not work. Can you assist me please?**
> 
> D:\Projects\ReactJS\vidly-api-node\seed.js:41
> async function seed() {
> ^^^^^^^^
> SyntaxError: Unexpected token function
> at createScript (vm.js:56:10)
> at Object.runInThisContext (vm.js:97:10)
> at Module._compile (module.js:542:28)
> at Object.Module._extensions..js (module.js:579:10)
> at Module.load (module.js:487:32)
> at tryModuleLoad (module.js:446:12)
> at Function.Module._load (module.js:438:3)
> at Module.runMain (module.js:604:10)

Easiest fix would be to make sure your node version is at least 7.6 or above
(version 7.6 being when async/await was introduced to node)

**Comment by rajeevkuruganti** [comment]
Thanks. I am good.
