### ISSUE TITLE
September 2020: Unable to add new movies

### ISSUE THREAD

**Issue by yitbareck** [mosh-hamedani/vidly-api-node#37]
Hello there,
Whenever I try to add new movies via Postman I get a 404 error: "title" is required.
Here is my request body(row->JSON):
`{
  "title":"The Lord of The Rings",
  "numberInStock":2,
  "dailyRentalRate":5,
  "genreId":"5f607904cdb2ec2d701930a7"
}`

**Comment by yitbareck** [comment]
I just forgot to set the content-type header:
`'content-type': 'application/json'`

**Comment by souravkumardubey** [comment]
Hey could you please tell me how you resolved this issue.
This is what I'm getting,
ValidationError: Movies validation failed: name: Path `name` is required.

My JSON input in postman:
{
    "title": "Interstellar",
    "genreId": "6438333ac7beaa87d38b1616",
    "numberInStock": 3,
    "dailyRentalRate": 3
}
