### ISSUE TITLE
npm i not working coming from React Course

### ISSUE THREAD

**Issue by shessafridi** [mosh-hamedani/vidly-api-node#40]
This is the error I get when running `npm i`, please help

PS I:\Work\Learning React\vidly-api-node> npm i

> bcrypt@1.0.3 install I:\Work\Learning React\vidly-api-node\node_modules\bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v72-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@12.18.4 (node-v72 ABI) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v72-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@12.18.4 (node-v72 ABI) (falling back to source compile with node-gyp)
gyp ERR! find VS
gyp ERR!gyp find VS msvs_version not set from command line or npm config
 gypERR!  ERR!find VS
find VSgyp VCINSTALLDIR not set, not running in VS Command Prompt
 gyp ERR!ERR!  find VSfind VS msvs_version not set from command line or npm config
 could not use PowerShell to find Visual Studio 2017 or newer
gypgyp  ERR!ERR!  find VSfind VS VCINSTALLDIR not set, not running in VS Command Prompt
 looking for Visual Studio 2015
gypgyp  ERR!ERR!  find VSfind VS could not use PowerShell to find Visual Studio 2017 or newer
 - not found
gypgyp  ERR! find VSERR! looking for Visual Studio 2015
 gypfind VS  not looking for VS2013 as it is only supported up to Node.js 8
ERR!gyp  find VSERR! - not found
 gypfind VS
ERR!gyp  find VSERR! not looking for VS2013 as it is only supported up to Node.js 8
 gypfind VS  **************************************************************
ERR!gyp  find VSERR!
 gypfind VS  You need to install the latest version of Visual Studio
ERR!gyp  find VSERR! **************************************************************
 gypfind VS  including the "Desktop development with C++" workload.
ERR!gyp  find VSERR! You need to install the latest version of Visual Studio
 gypfind VS  For more information consult the documentation at:
ERR!gyp  find VSERR! including the "Desktop development with C++" workload.
 gypfind VS  https://github.com/nodejs/node-gyp#on-windows
ERR!gyp  find VSERR! For more information consult the documentation at:
 gypfind VS  **************************************************************
ERR!gyp  find VSERR! https://github.com/nodejs/node-gyp#on-windows
 gypfind VS
ERR! find VS **************************************************************
gyp ERR! find VS
gyp gypERR!  ERR!configure error
configure errorgyp
 gypERR!  stackERR! Error: Could not find any Visual Studio installation to use
 gypstack  Error: Could not find any Visual Studio installation to use
ERR!gyp  ERR!stack      at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
stackgyp     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
 gyp ERR!ERR!  stackstack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gypgyp  ERR!ERR!  stackstack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gypgyp  ERR!ERR!  stackstack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gypgyp  ERR!ERR!  stackstack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gypgyp  ERR!ERR!  stackstack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp      at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gypERR!  ERR!stack      at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gypstack      at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
ERR!gyp  stackERR!     at ChildProcess.exithandler (child_process.js:310:5)
gyp  stackERR!     at ChildProcess.exithandler (child_process.js:310:5)
gyp  stackERR!     at ChildProcess.emit (events.js:315:20)
 gypstack      at ChildProcess.emit (events.js:315:20)
gypERR!  ERR!stack      at maybeClose (internal/child_process.js:1021:16)
stackgyp     at maybeClose (internal/child_process.js:1021:16)
 gypERR!  ERR!System  Windows_NT 10.0.19041
Systemgyp Windows_NT 10.0.19041
 ERR! gyp commandERR! "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=I:\\Work\\Learning React\\vidly-api-node\\node_modules\\bcrypt\\lib\\binding\\bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=I:\\Work\\Learning React\\vidly-api-node\\node_modules\\bcrypt\\lib\\binding"
 gypcommand  "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=I:\\Work\\Learning React\\vidly-api-node\\node_modules\\bcrypt\\lib\\binding\\bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=I:\\Work\\Learning React\\vidly-api-node\\node_modules\\bcrypt\\lib\\binding"
ERR!gyp  cwdERR! I:\Work\Learning React\vidly-api-node\node_modules\bcrypt
 gypcwd  I:\Work\Learning React\vidly-api-node\node_modules\bcrypt
ERR!gyp  node -vERR! v12.18.4
 gypnode -v  v12.18.4
ERR!gyp  node-gyp -vERR! v5.1.0
 gypnode-gyp -v  v5.1.0
ERR!gyp  not okERR!
 not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=I:\Work\Learning React\vidly-api-node\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=I:\Work\Learning React\vidly-api-node\node_modules\bcrypt\lib\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (I:\Work\Learning React\vidly-api-node\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Windows_NT 10.0.19041
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "I:\\Work\\Learning React\\vidly-api-node\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd I:\Work\Learning React\vidly-api-node\node_modules\bcrypt
node-pre-gyp ERR! node -v v12.18.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=I:\Work\Learning React\vidly-api-node\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=I:\Work\Learning React\vidly-api-node\node_modules\bcrypt\lib\binding' (1)
npm WARN vidly@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@1.0.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Shess\AppData\Roaming\npm-cache\_logs\2020-09-28T20_25_34_844Z-debug.log

**Comment by mina-kianrad** [comment]
Try this,
https://github.com/kelektiv/node.bcrypt.js/issues/432

**Comment by shessafridi** [comment]
> Try this,
> https://github.com/kelektiv/node.bcrypt.js/issues/432

I fixed it by manually removing bcrypt from package.json and then manually installing it

**Comment by Arsalon-amini** [comment]
The version of bycrpt Mosh uses in this course has been versioned up and it has created breaking changes. To fix this issue with npm i of bycrpt. Uninstall bycrpt in the terminal or remove from package.json under dependencies. Then run npm i bycrpt and the latest version will be installed in the node modules. This will fix your issues.
