### ISSUE TITLE
npm install bug -> bcrypt@1.0.3 library 

### ISSUE THREAD

**Issue by Roi467** [mosh-hamedani/vidly-api-node#41]
Hello,

I learn to react with mosh at his website and we need to install this for the backend to vidly project but I got an error when I tried to install this library... I checked the library npm and it been told that this library was down from sever

what should I do now? I stuck and cannot move forward with my course.

![image](https://user-images.githubusercontent.com/46962884/97312374-16a03780-186e-11eb-9a95-575768f1880f.png)

**Comment by mj-111** [comment]
The version of the bcrypt is different between what Mosh has and what you
have installed on your system. That's because Mosh has the older version.
To fix it:
1- Remove the bcrypt from package.json
2- install bcrypt again, *npm i bcrypt   --> this will install the latest
version*

**Comment by Roi467** [comment]
Thank u
