### ISSUE TITLE
Cannot get users API

### ISSUE THREAD

**Issue by arhoyFin** [mosh-hamedani/vidly-api-node#5]
I was able to get the movies and genre db working, but when I type 

> http://localhost:3900/api/users

it says `Cannot get API users`
If I type 

> http://localhost:3900/api/movies 
Then I am able to see all the movies in compass database.

 I follow all the steps above

**Comment by arhoyFin** [comment]
It is working properly, I made a silly typo mistake

**Comment by frankelly001** [comment]
Am having the same problem "Cannot GET /api/users" from http://localhost:3900/api/users, i did exactly as u instructed, still the same problem only movies and genres api worked, am stucked at users
